_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 30
                - 52
                - 55
            "2":
                - 1
                - 30
                - 52
                - 55
            "3":
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
